### ISSUE TITLE
Can't install swisseph (NaN dependency)

### ISSUE THREAD

**Issue by sjp8** [mivion/swisseph#21]
After updating node to v4.2.x, errors occur when making the c code in `npm install`.

Updating package.json to the following latest dependency versions fixed the error, in my [own repository](https://bitbucket.org/sjp8/swisseph/commits/65b67558cc0ef32285d7709e9404c952268a7b3b).
```
├── merge@1.2.0
├── nan@2.1.0
└── node-gyp@3.0.3 (graceful-fs@4.1.2, semver@5.0.3, osenv@0.1.3, fstream@1.0.8, nopt@3.0.4, minimatch@1.0.0, which@1.2.0, tar@1.0.3, mkdirp@0.5.1, glob@4.5.3, rimraf@2.4.3, path-array@1.0.0, npmlog@1.2.1, request@2.65.0)
```

Here are the errors. It seems that the nan module is mainly to blame, but have not isolated it.
```
../node_modules/nan/nan.h:324:27: error: redefinition of
      'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
```

```
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace
      'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
```

```
../node_modules/nan/nan.h:772:12: error: no viable conversion from
      'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Thanks!

**Comment by sjp8** [comment]
Added pull request.

**Comment by mivion** [comment]
Thanks for help!
Merged.
